insert Card (Spanish, English) values ('bien', 'good')
insert Card (Spanish, English) values ('ayudar', 'help')
insert Card (Spanish, English) values ('apellido', 'last name')
insert Card (Spanish, English) values ('calle', 'street')
insert Card (Spanish, English) values ('puerco', 'pig')
insert Card (Spanish, English) values ('hotel', 'hotel')
insert Card (Spanish, English) values ('invierno', 'winter')
insert Card (Spanish, English) values ('enero', 'January')
insert Card (Spanish, English) values ('tamaño', 'size')
insert Card (Spanish, English) values ('despacio', 'slowly')
insert Card (Spanish, English) values ('carta', 'letter, menu')
insert Card (Spanish, English) values ('derecho', 'straight, direct')
insert Card (Spanish, English) values ('lentamente', 'slowly')
insert Card (Spanish, English) values ('cartera', 'wallet')
insert Card (Spanish, English) values ('bajo', 'low, short, under')
insert Card (Spanish, English) values ('al lado de', 'next to')
insert Card (Spanish, English) values ('cerca', 'near')
insert Card (Spanish, English) values ('pobre', 'poor')
insert Card (Spanish, English) values ('bastante', 'enough')
insert Card (Spanish, English) values ('bonita', 'pretty')
insert Card (Spanish, English) values ('lejos', 'far')
insert Card (Spanish, English) values ('enojado', 'angry')
insert Card (Spanish, English) values ('triste', 'sad')
insert Card (Spanish, English) values ('feliz', 'happy')
insert Card (Spanish, English) values ('pequeño', 'small')
insert Card (Spanish, English) values ('aburrido', 'bored')
insert Card (Spanish, English) values ('comida', 'meal, food')
insert Card (Spanish, English) values ('cena', 'dinner')
insert Card (Spanish, English) values ('suerte', 'luck')
insert Card (Spanish, English) values ('sueño', 'dream, sleep')
insert Card (Spanish, English) values ('pais', 'country')
insert Card (Spanish, English) values ('idioma', 'language')
insert Card (Spanish, English) values ('calor', 'heat')
insert Card (Spanish, English) values ('cosa', 'thing')
insert Card (Spanish, English) values ('alguno', 'something')
insert Card (Spanish, English) values ('nunca', 'never')
insert Card (Spanish, English) values ('cero', 'zero')
insert Card (Spanish, English) values ('gordo', 'fat')
insert Card (Spanish, English) values ('precio', 'price')
insert Card (Spanish, English) values ('cuchara', 'spoon')
insert Card (Spanish, English) values ('cuchillo', 'knife')
insert Card (Spanish, English) values ('abrìgo', 'coat')
insert Card (Spanish, English) values ('hincha', 'fan (enthusiast; as in sports)')
insert Card (Spanish, English) values ('casi', 'almost')
insert Card (Spanish, English) values ('similar', 'similar')
insert Card (Spanish, English) values ('parecido', 'like')
insert Card (Spanish, English) values ('brazo', 'arm')
insert Card (Spanish, English) values ('pierna', 'leg')
insert Card (Spanish, English) values ('pata', 'paw')
insert Card (Spanish, English) values ('alguien', 'someone')
insert Card (Spanish, English) values ('todavía', 'still/yet')
insert Card (Spanish, English) values ('nuestra', 'our')
insert Card (Spanish, English) values ('ninguno', 'none')
insert Card (Spanish, English) values ('nadie', 'nobody')
insert Card (Spanish, English) values ('puente', 'bridge/4-day weekend')
insert Card (Spanish, English) values ('a lo mejor', 'at best')
insert Card (Spanish, English) values ('a la mejor', 'maybe')
insert Card (Spanish, English) values ('ánima', 'spirit')
insert Card (Spanish, English) values ('anillo', 'ring')
insert Card (Spanish, English) values ('dedo', 'finger')
insert Card (Spanish, English) values ('luz', 'light')
insert Card (Spanish, English) values ('caja', 'box')
insert Card (Spanish, English) values ('pesadillo', 'nightmare')
insert Card (Spanish, English) values ('además', 'besides/also')
insert Card (Spanish, English) values ('ya', 'already')
insert Card (Spanish, English) values ('obra de arte', 'work of art')
insert Card (Spanish, English) values ('pieza', 'part/piece')
insert Card (Spanish, English) values ('truco', 'trick')
insert Card (Spanish, English) values ('paquete', 'package')
insert Card (Spanish, English) values ('estafa', 'fraud/con/swindle')
insert Card (Spanish, English) values ('engañar', 'to cheat')
insert Card (Spanish, English) values ('espia', 'spy')
insert Card (Spanish, English) values ('bebé', 'baby')
insert Card (Spanish, English) values ('callejón', 'alley')
insert Card (Spanish, English) values ('demasiado', 'too much')
insert Card (Spanish, English) values ('bolsa', 'bag')
insert Card (Spanish, English) values ('bolsillo', 'pocket')
insert Card (Spanish, English) values ('nivel', 'level')
insert Card (Spanish, English) values ('consolar', 'to console (comfort)')
insert Card (Spanish, English) values ('entre', 'between')
insert Card (Spanish, English) values ('taller', 'workshop/garage')
insert Card (Spanish, English) values ('tienda', 'store')
insert Card (Spanish, English) values ('ira', 'anger')
insert Card (Spanish, English) values ('segundo', 'second (time)')
insert Card (Spanish, English) values ('pero', 'but')
insert Card (Spanish, English) values ('perro', 'dog')
insert Card (Spanish, English) values ('manzana', 'apple')
insert Card (Spanish, English) values ('viejo', 'old')
insert Card (Spanish, English) values ('edad', 'age')
insert Card (Spanish, English) values ('oro', 'gold')
insert Card (Spanish, English) values ('juerga', 'spree/binge')
insert Card (Spanish, English) values ('borracho', 'drunk')
insert Card (Spanish, English) values ('fuerte', 'strong')
insert Card (Spanish, English) values ('parte', 'part')
insert Card (Spanish, English) values ('joven', 'young')
insert Card (Spanish, English) values ('gente', 'people')
insert Card (Spanish, English) values ('maneras', 'manners/ways')
insert Card (Spanish, English) values ('sociedad', 'society')
insert Card (Spanish, English) values ('canal', 'canal/channel')
insert Card (Spanish, English) values ('riego', 'irregation')
insert Card (Spanish, English) values ('disponible', 'available/disposable')
insert Card (Spanish, English) values ('par', 'pair')
insert Card (Spanish, English) values ('soporte', 'support (n)')
insert Card (Spanish, English) values ('pilar', 'pillar')
insert Card (Spanish, English) values ('montaña', 'mountain')
insert Card (Spanish, English) values ('llanura', 'plain (flat area)')
insert Card (Spanish, English) values ('francamente', 'frankly')
insert Card (Spanish, English) values ('claramente', 'plainly')
insert Card (Spanish, English) values ('la entrada', 'entrance')
insert Card (Spanish, English) values ('el mesero', 'waiter')
insert Card (Spanish, English) values ('el garzón', 'waiter')
insert Card (Spanish, English) values ('abusadora', 'heartbreaker')
insert Card (Spanish, English) values ('labios (careful with the last vowel)', 'lips')
insert Card (Spanish, English) values ('además', 'also/besides')
insert Card (Spanish, English) values ('oscuro', 'dark')
insert Card (Spanish, English) values ('sombrío', 'somber/dismal')
insert Card (Spanish, English) values ('mate', 'mate')
insert Card (Spanish, English) values ('amortiguado', 'cushioned')
insert Card (Spanish, English) values ('brillo', 'brightness')
insert Card (Spanish, English) values ('calcetines', 'socks')
insert Card (Spanish, English) values ('pared', 'wall')
insert Card (Spanish, English) values ('dentro', 'inside/within')
insert Card (Spanish, English) values ('dentro de nada', 'in no time/right away')
insert Card (Spanish, English) values ('da a luz', 'gives birth (give to light)')
insert Card (Spanish, English) values ('oferta', 'offer')
insert Card (Spanish, English) values ('pincho', 'spike')
insert Card (Spanish, English) values ('mariscos', 'seafood')
insert Card (Spanish, English) values ('camarón', 'shrimp')
insert Card (Spanish, English) values ('a menudo', 'often')
insert Card (Spanish, English) values ('guión', 'script, screenplay')
insert Card (Spanish, English) values ('nacer', 'to be born')
insert Card (Spanish, English) values ('irrumpir', 'burst, break')
insert Card (Spanish, English) values ('historia', 'history, story')
insert Card (Spanish, English) values ('tremenda', 'tremendous, terrible')
insert Card (Spanish, English) values ('galardonar', 'reward')
insert Card (Spanish, English) values ('subsiguiente', 'subsequent')
insert Card (Spanish, English) values ('atroz', 'atrocious, awful')
insert Card (Spanish, English) values ('adquirir', 'to acquire')
insert Card (Spanish, English) values ('antologia', 'anthology')
insert Card (Spanish, English) values ('destacado', 'outstanding')
insert Card (Spanish, English) values ('cultivo', 'culture, cultivation, crop')
insert Card (Spanish, English) values ('duros', 'difficult, strong, tough, severe')
insert Card (Spanish, English) values ('fundador', 'founder')
insert Card (Spanish, English) values ('baloncesto', 'basketball')
insert Card (Spanish, English) values ('medir', 'to measure')
insert Card (Spanish, English) values ('prisa', 'hurry, rush')
insert Card (Spanish, English) values ('sabor', 'flavor, savor')
insert Card (Spanish, English) values ('sustancia', 'substance')
insert Card (Spanish, English) values ('bigote', 'mustache')
insert Card (Spanish, English) values ('vela', 'candle')
insert Card (Spanish, English) values ('mensaje', 'message')
insert Card (Spanish, English) values ('bromear', 'to joke')
insert Card (Spanish, English) values ('jabón', 'soap')
insert Card (Spanish, English) values ('suelto', 'loose')
insert Card (Spanish, English) values ('odio/odiado', 'hate/hated')
insert Card (Spanish, English) values ('presumido', 'smug/conceited')
insert Card (Spanish, English) values ('barato', 'cheap/inexpensive')
insert Card (Spanish, English) values ('mocoso', 'brat/punk')
insert Card (Spanish, English) values ('perrito', 'puppy')
insert Card (Spanish, English) values ('cachorro', 'puppy')
insert Card (Spanish, English) values ('celoso', 'jealous')
insert Card (Spanish, English) values ('elenco', 'cast (i.e. of a movie)')
insert Card (Spanish, English) values ('pelota', 'ball')
insert Card (Spanish, English) values ('pelo', 'hair')
insert Card (Spanish, English) values ('lástima', 'pity')
insert Card (Spanish, English) values ('despedida', 'farewell/goodbye')
insert Card (Spanish, English) values ('oso', 'bear')
insert Card (Spanish, English) values ('pájaro', 'bird')
insert Card (Spanish, English) values ('tortuga', 'turtle')
insert Card (Spanish, English) values ('cangrejo', 'crab')
insert Card (Spanish, English) values ('caballo', 'horse')
insert Card (Spanish, English) values ('araña', 'spider')
insert Card (Spanish, English) values ('mono', 'monkey')
insert Card (Spanish, English) values ('disfrutar', 'to enjoy')
insert Card (Spanish, English) values ('máquina', 'machine')
insert Card (Spanish, English) values ('torre', 'tower')
insert Card (Spanish, English) values ('costa', 'coast or cost/price')
insert Card (Spanish, English) values ('capítulo', 'chapter/episode')
insert Card (Spanish, English) values ('tarea', 'task/job')
insert Card (Spanish, English) values ('ausencia', 'absence')
insert Card (Spanish, English) values ('piscina', 'pool')
insert Card (Spanish, English) values ('premio', 'prize')
insert Card (Spanish, English) values ('tema', 'theme')
insert Card (Spanish, English) values ('conocimiento', 'knowledge')
insert Card (Spanish, English) values ('imagen', 'image')
insert Card (Spanish, English) values ('codigo', 'code')
insert Card (Spanish, English) values ('calidad', 'quality')
insert Card (Spanish, English) values ('crecimiento', 'growth')
insert Card (Spanish, English) values ('mochila', 'backpack')
insert Card (Spanish, English) values ('creación', 'creation')
insert Card (Spanish, English) values ('asunto', 'matter/issue/affair')
insert Card (Spanish, English) values ('juicio', 'trial')
insert Card (Spanish, English) values ('juez', 'judge')
insert Card (Spanish, English) values ('polvo', 'dust')
insert Card (Spanish, English) values ('red (not a typo; Spanish)', 'hairnet')
insert Card (Spanish, English) values ('termino', 'term (as in agreement)/end')
insert Card (Spanish, English) values ('altura', 'height')
insert Card (Spanish, English) values ('escena', 'scene')
insert Card (Spanish, English) values ('pensamiento', 'thought')
insert Card (Spanish, English) values ('competencia', 'competition/competance')
insert Card (Spanish, English) values ('propósito', 'purpose')
insert Card (Spanish, English) values ('vecina', 'neighbor')
insert Card (Spanish, English) values ('campesino', 'farmer')
insert Card (Spanish, English) values ('herido', 'wounded')
insert Card (Spanish, English) values ('sonrisa', 'smile')
insert Card (Spanish, English) values ('armistad', 'friendship')
insert Card (Spanish, English) values ('alegría', 'happiness')
insert Card (Spanish, English) values ('soledad', 'loneliness')
insert Card (Spanish, English) values ('esperanza', 'hope')
insert Card (Spanish, English) values ('sala', 'living room')
insert Card (Spanish, English) values ('sorpresa', 'surprise')
insert Card (Spanish, English) values ('temor', 'fear')
insert Card (Spanish, English) values ('esponja', 'sponge')
insert Card (Spanish, English) values ('autor', 'author')
insert Card (Spanish, English) values ('deseo', 'desire')
insert Card (Spanish, English) values ('sentimientos', 'feelings')
insert Card (Spanish, English) values ('placer', 'pleasure')
insert Card (Spanish, English) values ('cuervo', 'crow')
insert Card (Spanish, English) values ('feo', 'ugly')
insert Card (Spanish, English) values ('dueño', 'owner')
insert Card (Spanish, English) values ('pista', 'clue')
insert Card (Spanish, English) values ('arena', 'sand')
insert Card (Spanish, English) values ('lugar', 'place')
insert Card (Spanish, English) values ('pasto', 'grass')
insert Card (Spanish, English) values ('pasta', 'pasta/paste')
insert Card (Spanish, English) values ('esquina', 'corner')
insert Card (Spanish, English) values ('madera', 'wood')
insert Card (Spanish, English) values ('naturaleza', 'nature')
insert Card (Spanish, English) values ('planeta', 'planet')
insert Card (Spanish, English) values ('piedra', 'stone')
insert Card (Spanish, English) values ('hoja', 'leaf')
insert Card (Spanish, English) values ('bosque', 'woods')
insert Card (Spanish, English) values ('raíz', 'root')
insert Card (Spanish, English) values ('paisaje', 'scenery')
insert Card (Spanish, English) values ('cerebro', 'brain')
insert Card (Spanish, English) values ('cadena', 'chain')
insert Card (Spanish, English) values ('hueso', 'bone')
insert Card (Spanish, English) values ('viento', 'wind')
insert Card (Spanish, English) values ('humo', 'smoke')
insert Card (Spanish, English) values ('búho', 'owl')
insert Card (Spanish, English) values ('helado', 'ice cream')
insert Card (Spanish, English) values ('mariposa', 'butterfly')
insert Card (Spanish, English) values ('forma', 'shape')
insert Card (Spanish, English) values ('gesto', 'gesture')
insert Card (Spanish, English) values ('sencilla', 'simple')
insert Card (Spanish, English) values ('compromiso', 'commitment')
insert Card (Spanish, English) values ('reconoce', 'acknowledge')
insert Card (Spanish, English) values ('comportamiento', 'behavior')
insert Card (Spanish, English) values ('sombra', 'shadow')
insert Card (Spanish, English) values ('puesto', 'post/job/position')
insert Card (Spanish, English) values ('esfuerzo', 'effort')
insert Card (Spanish, English) values ('propuesta', 'proposal')
insert Card (Spanish, English) values ('recurso', 'resource')
insert Card (Spanish, English) values ('zorro', 'fox')
insert Card (Spanish, English) values ('ruido', 'noise')
insert Card (Spanish, English) values ('cargo', 'position/load')
insert Card (Spanish, English) values ('cargos', 'charges')
insert Card (Spanish, English) values ('pausa', 'pause')
insert Card (Spanish, English) values ('orden', 'order')
insert Card (Spanish, English) values ('curso', 'course')
insert Card (Spanish, English) values ('fracaso', 'failure')
insert Card (Spanish, English) values ('torneo', 'tournament')
insert Card (Spanish, English) values ('gol', 'goal')
insert Card (Spanish, English) values ('jugador', 'player')
insert Card (Spanish, English) values ('equipo', 'team/equipment')
insert Card (Spanish, English) values ('estadio', 'stadium')
insert Card (Spanish, English) values ('campeón', 'champion')
insert Card (Spanish, English) values ('carrera', 'race')
insert Card (Spanish, English) values ('liga', 'league (team)')
insert Card (Spanish, English) values ('nariz', 'nose')
insert Card (Spanish, English) values ('cuello', 'neck')
insert Card (Spanish, English) values ('piel', 'skin')
insert Card (Spanish, English) values ('pecho', 'chest')
insert Card (Spanish, English) values ('hombro', 'shoulder')
insert Card (Spanish, English) values ('rodillas', 'knees')
insert Card (Spanish, English) values ('tratamiento', 'treatment')
insert Card (Spanish, English) values ('adequado', 'suitable/proper')
insert Card (Spanish, English) values ('codo', 'elbow')
insert Card (Spanish, English) values ('recuerdo', 'memory')
insert Card (Spanish, English) values ('enfermedad', 'disease')
insert Card (Spanish, English) values ('riesgo', 'risk')
insert Card (Spanish, English) values ('dosis', 'dose')
insert Card (Spanish, English) values ('presión', 'pressure')
insert Card (Spanish, English) values ('síntoma', 'symptom')
insert Card (Spanish, English) values ('diagnóstico', 'diagnosis')
insert Card (Spanish, English) values ('órgano', 'organ')
insert Card (Spanish, English) values ('lágrimas', 'tears')
insert Card (Spanish, English) values ('olor', 'smell/odor')
insert Card (Spanish, English) values ('mente', 'mind')
insert Card (Spanish, English) values ('grave', 'serious')
insert Card (Spanish, English) values ('cifra', 'number/figure')
insert Card (Spanish, English) values ('deuda', 'debt')
insert Card (Spanish, English) values ('valores', 'values')
insert Card (Spanish, English) values ('ingresos', 'income')
insert Card (Spanish, English) values ('fuente', 'source')
insert Card (Spanish, English) values ('porcentaje', 'percentage')
insert Card (Spanish, English) values ('reunión', 'meeting')
insert Card (Spanish, English) values ('inversión', 'investment')
insert Card (Spanish, English) values ('prensa', 'press')
insert Card (Spanish, English) values ('lenguaje', 'language')
insert Card (Spanish, English) values ('jardín', 'yard/garden')
insert Card (Spanish, English) values ('grito', 'scream/shout')
insert Card (Spanish, English) values ('postal', 'postcard')
insert Card (Spanish, English) values ('campesino', 'farmer')
insert Card (Spanish, English) values ('fe', 'faith')
insert Card (Spanish, English) values ('espejo', 'mirror')
insert Card (Spanish, English) values ('cruz', 'cross')
insert Card (Spanish, English) values ('edificio', 'building')
insert Card (Spanish, English) values ('un rato', 'for a while')
insert Card (Spanish, English) values ('hermosa', 'beautiful')
